drop table if exists users, item, bookings, requests, comments;

CREATE TABLE IF NOT EXISTS users (
	id integer generated by default as identity not null,
	name varchar(100) NOT NULL,
	email varchar(100) NOT NULL,
	CONSTRAINT pk_user PRIMARY KEY (id),
	CONSTRAINT UQ_USER_EMAIL unique (email)
);

CREATE TABLE IF NOT EXISTS item (
    id integer generated by default as identity not null,
    name varchar(150) not null,
    description varchar(300) not null,
    is_available boolean not null,
    owner_id integer not null references users (id),
    request integer,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id integer generated by default as identity not null,
    start_booking timestamp not null,
    end_booking timestamp not null,
    item_id integer not null,
    user_id integer not null,
    status varchar not null,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests (
    id integer generated by default as identity not null,
    description varchar(300) not null,
    requestor_id integer not null,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments (
    id integer generated by default as identity not null,
    text varchar(1000) not null,
    item_id integer not null,
    author_id integer not null,
    created timestamp not null,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);